# BroadCast

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, -1])
result_add = arr + vector
print("Sum :", result_add)

result_mult = arr * 2
print("product :", result_mult)

print("addition : \n",result_mult + result_add)
# print(arr)

Sum : [[2 2 2]
 [5 5 5]
 [8 8 8]]
product : [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
addition : 
 [[ 4  6  8]
 [13 15 17]
 [22 24 26]]


# Random number

In [ ]:
rand_num = np.random.randint(1,51, size=(5,5))
print("Original : \n", rand_num)

# filter values > 25 and replace it with 0

rand_num[rand_num > 25] = 0
print("Modified DS : \n", rand_num)

# Summary
print('Sum', np.sum(rand_num))
print('Min', np.min(rand_num))
print('Max', np.max(rand_num))
print('Mean', np.mean(rand_num))
print('Standard deviation', np.std(rand_num))

Original : 
 [[28 48  1 34 35]
 [37  1  8 10 26]
 [29 25 38 46 38]
 [24  7 24 25 39]
 [ 2 34 36 34 20]]
Modified DS : 
 [[ 0  0  1  0  0]
 [ 0  1  8 10  0]
 [ 0 25  0  0  0]
 [24  7 24 25  0]
 [ 2  0  0  0 20]]
Sum 147
Min 0
Max 25
Mean 5.88
Standard deviation 9.287927648297009


In [ ]:
Dataset = np.random.randint(1, 10, size=(3,3))
print(Dataset)
print('Sum', np.sum(Dataset, axis=0))
print('Sum', np.sum(Dataset, axis=1))

[[6 6 3]
 [3 8 6]
 [1 1 3]]
Sum [10 15 12]
Sum [15 17  5]


In [ ]:
data = {
  "Name": ['Alice', "Bob", ]
}